 AddLocationForm:
 
<AddLocationForm>:
    search_input: search_box
    orientation: 'vertical'
    BoxLayout:
        size_hint_y: None
        height:'35dp'
    TextInput:
        id: search_box
        size_hint_x: 50
    Button:
        size_hint_x: 25
        text: 'Search'
        on_press: root.search_location()
    Button:
        size_hint_x: 25
        text: 'Current location'
    ListView:
        item_string: []